# Generated by Django 5.2.1 on 2025-10-08 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("accounts", "0002_initial"),
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("gpa", models.FloatField(blank=True, null=True)),
                ("is_gpa_weighted", models.BooleanField(default=False)),
                ("sat", models.PositiveIntegerField(blank=True, null=True)),
                ("act", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_budget",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum Yearly School Budget in USD",
                        null=True,
                    ),
                ),
                (
                    "max_budget",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum Yearly School Budget in USD",
                        null=True,
                    ),
                ),
                ("grad_year", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("positions", models.ManyToManyField(blank=True, to="sports.position")),
                (
                    "posted_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.coach"),
                ),
                (
                    "sport",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sports.sport"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpeningExamScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academics.exam"),
                ),
                (
                    "opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openings.opening",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="opening",
            name="exam_scores",
            field=models.ManyToManyField(
                blank=True,
                through="openings.OpeningExamScore",
                through_fields=("opening", "exam"),
                to="academics.exam",
            ),
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("is_new", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("status_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.athlete",
                    ),
                ),
                (
                    "opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openings.opening",
                    ),
                ),
            ],
            options={
                "unique_together": {("opening", "athlete")},
            },
        ),
    ]
