# Generated by Django 5.2.1 on 2025-10-08 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("accounts", "0001_initial"),
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="clubs",
            field=models.ManyToManyField(blank=True, to="sports.club"),
        ),
        migrations.AddField(
            model_name="athlete",
            name="highschool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.highschool",
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="leagues",
            field=models.ManyToManyField(blank=True, to="sports.league"),
        ),
        migrations.AddField(
            model_name="athlete",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sports.position",
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sports.sport",
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.university",
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.university",
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.coach",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.university",
            ),
        ),
    ]
