# Generated by Django 5.2.1 on 2025-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="height",
            field=models.FloatField(blank=True, help_text="Height in inches", null=True),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="highschool_grad_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="weight",
            field=models.FloatField(blank=True, help_text="Weight in pounds", null=True),
        ),
    ]
