# Generated by Django 5.2.1 on 2025-11-18 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_athlete_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="notify_applications_in_app",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="notify_feedback_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="notify_messages_in_app",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="notify_product_updates_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="notify_profile_updates_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="notify_profile_updates_in_app",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="NotificationToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("athlete", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.athlete")),
                ("coach", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.coach")),
            ],
            options={
                "unique_together": {("athlete", "coach")},
            },
        ),
    ]
