# Generated by Django 5.2.1 on 2025-10-08 22:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AthleteExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("date_taken", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(choices=[("AP", "AP"), ("IB", "IB")], max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Highschool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("logo", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "background_image",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                (
                    "athletic_division",
                    models.CharField(
                        choices=[
                            ("NCAA Division I", "NCAA Division I"),
                            ("NCAA Division II", "NCAA Division II"),
                            ("NCAA Division III", "NCAA Division III"),
                            ("NAIA", "NAIA"),
                            ("NJCAA", "NJCAA"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "acceptance_rate",
                    models.FloatField(blank=True, help_text="Percentage (0-100)", null=True),
                ),
                ("logo", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "background_image",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
    ]
