# Generated by Django 5.2.1 on 2025-10-08 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteexam",
            name="athlete",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.athlete"),
        ),
        migrations.AddField(
            model_name="athleteexam",
            name="exam",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academics.exam"),
        ),
        migrations.AddField(
            model_name="highschool",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.address",
            ),
        ),
    ]
