# Generated by Django 5.2.1 on 2025-11-18 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityEmailDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=255, unique=True)),
                (
                    "university",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academics.university"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="university",
            name="email_domains",
            field=models.ManyToManyField(blank=True, related_name="universities", to="academics.universityemaildomain"),
        ),
    ]
